feat: update

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -19,7 +19,8 @@ find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
         if ! "$bootstrap"; then
             echo "Error: bootstrap '$bootstrap' failed" >&2
             # exit 1
+        else
+            echo "Error: bootstrap '$bootstrap' success" >&2
         fi
     fi
 done
-
